#SQL Server
spring.datasource.url: jdbc:mysql://localhost:3306/gamestore?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: root

# Show or not log for each sql query
spring.jpa.show-sql: true
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
# spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5InnoDBDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto : none
logging.level.org.hibernate.SQL :  DEBUG